version: "3.6"

services:
  pax-service:
    dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - 5003:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=mysql+pymysql://my7xouigfdzw8m0h:ghuabqxddo7xab0h@zy4wtsaw3sjejnud.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/cyofgkwuvz6mathq
    command: python manage.py run -h 0.0.0.0